/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import strapiPluginIconhub from "@arshiash80/strapi-plugin-iconhub/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "strapi-plugin-iconhub": strapiPluginIconhub,
    "strapi-cloud": strapiCloud,
    "users-permissions": usersPermissions,
  },
});
